### ISSUE TITLE
[Request] Add 64bit support for fb2k v2

### ISSUE THREAD

**Issue by snowbie** [Meowski/foo_paulstretch#1]

**Comment by Meowski** [comment]
Cool.  I wasn't aware of this.  After I've had time to properly poke around the SDK I'll push an update here. Might be a while, though.

In the meantime, I've compiled an x64 version that should work with the x64 v2 beta.
[foo_paulstretch-x64.zip](https://github.com/Meowski/foo_paulstretch/files/9638474/foo_paulstretch-x64.zip)

**Comment by Meowski** [comment]
Put an alpha version on the releases section if you'd like to test it. I'll leave this issue open until fb2k leaves beta and I'm more confident there's no bugs.

**Comment by AnatolyIliev** [comment]
just wanted to say this plugin is fucking excellent, couldn't believe someone had made just what i was looking for

**Comment by Meowski** [comment]
Thank you! I'm glad others are finding this plugin useful.

It looks like fb2k v2 is stable now. I've built the plugin again, with the latest sdk, and I haven't managed to crash it yet, so I'll consider this closed.  Please do let me know if you discover any bugs.
